//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomiumSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwesomiumSharp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate IME.
        /// </summary>
        internal static string ActivateIME {
            get {
                return ResourceManager.GetString("ActivateIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add URL Filter.
        /// </summary>
        internal static string AddURLFilter {
            get {
                return ResourceManager.GetString("AddURLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel IME Composition.
        /// </summary>
        internal static string CancelIMEComposition {
            get {
                return ResourceManager.GetString("CancelIMEComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all URL filters.
        /// </summary>
        internal static string ClearAllURLFilters {
            get {
                return ResourceManager.GetString("ClearAllURLFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm IME Composition.
        /// </summary>
        internal static string ConfirmIMEComposition {
            get {
                return ResourceManager.GetString("ConfirmIMEComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Object.
        /// </summary>
        internal static string CreateObject {
            get {
                return ResourceManager.GetString("CreateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy Object.
        /// </summary>
        internal static string DestroyObject {
            get {
                return ResourceManager.GetString("DestroyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File.
        /// </summary>
        internal static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load URL.
        /// </summary>
        internal static string LoadURL {
            get {
                return ResourceManager.GetString("LoadURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Zoom.
        /// </summary>
        internal static string ResetZoom {
            get {
                return ResourceManager.GetString("ResetZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Find.
        /// </summary>
        internal static string StopFind {
            get {
                return ResourceManager.GetString("StopFind", resourceCulture);
            }
        }
    }
}
